GET http://localhost:3000/

### SEND FORM DATA

GET http://localhost:3000/songs

### SEND FORM DATA
GET http://localhost:3000/songs/1

### SEND FORM DATA

POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "Next Song",
    "artists": ["New Artist0", "New Artist1"],
    "releasedDate": "2024-09-29",
    "duration": "07:34"
}

### SEND FORM DATA

PATCH http://localhost:3000/songs/1

### SEND FORM DATA

DELETE http://localhost:3000/songs/1