GET http://localhost:3000/

### SEND FORM DATA

GET http://localhost:3000/songs

### SEND FORM DATA
GET http://localhost:3000/songs/1

### SEND FORM DATA

POST http://localhost:3000/songs

### SEND FORM DATA

PATCH http://localhost:3000/songs/1

### SEND FORM DATA

DELETE http://localhost:3000/songs/1